#!/bin/sh -x

username="smbtest$$"
password="$$"

echo "Creating a local test user called ${username}"
useradd -m "$username"

echo "Setting samba password for the ${username} user"
echo "${password}\n${password}" | smbpasswd -s -a ${username}

echo "Testing with incorrect password: must fail"
smbclient -L localhost -U ${username}%wrongpass && exit 1

echo "Testing with correct password: must work"
smbclient -L localhost -U ${username}%${password}

